### ISSUE TITLE
Sass 도입 어떠세요?

### ISSUE THREAD

**Issue by pdvonzoo** [teamdeepco/partstone#14]
css의 단점을 커버하기 위해 Sass를 도입하려고 합니다. 
의견 부탁드릴게요. 감사합니다. :)

@sejungkim @HTMLhead

**Comment by sejungkim** [comment]
제가 잘 몰라서 그러는데 혹시 Sass의 단점에는 뭐가 있을까요?
css의 단점은 충분히 느끼고 있긴 합니다. ㅋㅋㅋ

**Comment by HTMLhead** [comment]
@pdvonzoo 저는 찬성합니다. 만약 도입하자는 의견이 확립된다면 package.json 에 대한 sass환경 제작 이후에 pull request 부탁드립니다.

**Comment by pdvonzoo** [comment]
@sejungkim 단점이 상대적인것 같아서요~ css를 기준으로 봤을때 sass의 단점을 말씀하시는 건가요?

**Comment by pdvonzoo** [comment]
@HTMLhead 넵 새라랑 의견 조율한 후에 도입하게 되면 환경 설정하겠습니다 :)

**Comment by pdvonzoo** [comment]
@sejungkim css를 기준으로 한 단점이라면 sass는 환경 설정을 하기 위해 필요한 시간 비용이 있습니다. 또한 새로운 문법을 배우기 위한 시간도 필요할 것입니다. 하지만 간단한 문법을 익히고 사용을 한다면 더 큰 생산성으로 스타일을 적용할 수 있을것입니다.

**Comment by sejungkim** [comment]
넵! 저는 처음이지만 일단 써볼게요! 그럼 제가 sass 환경설정 관련 이슈 만들도록 하겠습니다!
